vmware/nsx-container-plugin-operator

- pkg/controller/pod/pod_controller.go
When any of the DS or NSX-NCP deployment is deleted, its spec from
sharedInfo is consumed to recreate the spec. However, we must not
change the spec in the sharedInfo as it's updated with resourceVersion
field which prohibits further usage of the spec.
> Allow DS and NCP deployment multiple recreations

- pkg/controller/configmap/config.go
- pkg/controller/configmap/config_test.go
- pkg/controller/configmap/configmap_controller.go
As NCP does not handle service CIDRs, if these are the only
item being updated on the network CR, NCP skips procesing
the resource status update.
This patch ensures the network CR is updated if necessary
even if the operator is not applying any change to NCP.
> Ensure service CIDRs are updated in any case

- pkg/controller/node/node_controller.go
For the VM on vSAN, the vmx_path has different format, e.g.
VM on VMFS:
vmx_path:
`/vmfs/volumes/<datastore-id>/control-plane-0/compute-0.vmx`
port_name:
`control-plane-0/compute-0.vmx@<tn-id>`
VM on vSAN:
vmx_path:
`/vmfs/volumes/vsan:<datastore-id>/e165115f-72e0-664d-a6c3-005056a7469a/compute-0.vmx`
port_name:
`e165115f-72e0-664d-a6c3-005056a7469a/compute-0.vmx@<tn-id>`
This patch changes the node port searching logic for the latter.
> Adapt the port searching rule for vSAN node VM

- pkg/controller/configmap/config.go
- pkg/controller/configmap/config_test.go
- pkg/controller/configmap/configmap_controller.go
- pkg/types/names.go
Retrieve nsx-secret to generate applied operator configmap for
checking if the configmap changed, in case the NCP pod is re-created
everytime when the operator starts.
> Retrieve nsx-secret to generate applied operator configmap

- pkg/controller/node/node_controller.go
When the operator tries to checked segment ports to tag for nodes,
it will skip handling the port with empty realized bindings.
> Skip checking port which doesn't have realized bindings

- pkg/controller/configmap/configmap_controller.go
In some case, the UpdateNetworkStatusError cannot be removed and the
clusteroperator nsx-ncp gets stuck in degraded status, this patch will
fix this issue.
> Set no degraded after the network status is successfully updated

- pkg/controller/configmap/config.go
1) Do not force wait_for_security_policy_sync=True
Allow the config map controller to not set this value
to True if already sent in the operator CM.
2) Add default setting for waiting_before_cni_response
Add a default 3-second delay for nsx-node-agent before
returning to CNI plugin.
> Update default settings for config map 

- cmd/manager/main.go
- deploy/operator.yaml
- olm-catalog/0.0.4/nsx-container-plugin-operator.v0.0.4.clusterserviceversion.yaml
- olm-catalog/0.0.4/operator.nsx.vmware.com_ncpinstalls_crd.yaml
- olm-catalog/make_zip_bundle.py
- olm-catalog/nsx-container-plugin-operator.package.yaml
- pkg/controller/configmap/configmap_controller.go
- pkg/controller/controller.go
- pkg/controller/node/node_controller.go
- pkg/controller/pod/pod_controller_test.go
- pkg/controller/statusmanager/status_manager.go
- pkg/controller/statusmanager/status_manager_test.go
This patch updates the CSV for the operator by:
- adding NcpInstalls CRD to permissions
- ensuring OLM will create ClusterRole for permissions
- Fixing various typos
- Adding descriptors for CRD spec and status fields
- Adjusting install modes to ensure only Own and Single Namespace
are supported
- ensuring hostNetwork permissions are given
- adding WATCH_NAMESPACE env variable to the deployment spec
The CSV version is therefore bumped to 0.0.4
A python utility to create the bundle zip for the latest CSV has
been added (make_zip_bundle.py)
In additioni, the operator code has been modified to support the
SingleNamespace install mode and ensuring it is not executed in
Multi or AllNamespace mode (in both cases it will default to
nsx-system-operator)
> Final CSV and support for custom Namespace

- pkg/controller/configmap/configmap_controller.go
A misplaced else was causing an error to be logged even if the
network status was successfully updated.
> Fix incorrectly placed else in update_network_status

- deploy/openshift4/lb-secret.yaml
- deploy/openshift4/nsx-secret.yaml
- deploy/openshift4/role_binding.yaml
- deploy/openshift4/service_account.yaml
The user will fail to get the file content from
raw.githubusercontent.com if we use the links.
This patch will remove the links and use the real
files as a replacement.
> Remove files link for yamls in /deploy

- README.md
Fix README by deleting unnecessary backquote 
The words, adaptor/cluster/nsx_api_managers/tier0_gateway_top_tier_router/external_ip_pools are not treated as inline code because of unnecessary backquote
> Fix README by deleting unnecessary backquote

- pkg/controller/pod/pod_controller.go
- pkg/controller/sharedinfo/shared_info.go
- pkg/controller/statusmanager/pod_status.go
- pkg/types/names.go
When the operator tries to update NetworkUnavaible from false to true,
it will wait 150 seconds to ensure that the nsx-node-agent is really
healthy as the liveness probe doesn't fail.
> Wait longer time to ensure the network status is really recovered

- pkg/controller/configmap/configmap_controller.go
The render lib will got an empty manifest because there's
addtional "---" in all-in-one yaml. This patch will filter
out that kind of invalid manifest.
> Ignore the empty manifest during applying objects

- Makefile
PR #93 renamed not only the image name, but also the executable
> Fix Makefile to preserve nsx-ncp-operator as binary the name

- Makefile
This will ensure the image built is also pushed to the
target registry
> Set latest tag when building operator image

- pkg/controller/configmap/configmap_controller.go
- pkg/controller/pod/pod_controller.go
- pkg/controller/pod/pod_controller_test.go
- pkg/types/utils.go
- pkg/types/utils_test.go
The user can delete nsx-ncp deployment or nsx-node-agent, nsx-ncp-bootstrap
Daemon Sets. If they are deleted when the operator is not running, the
operator should create them upon startup
> Check and create NCP resources at startup

- pkg/controller/statusmanager/pod_status.go
**The issue brief:**
This issue was found during test to access pod status startTime field: which led to operator crash and restarted.
test log as below:
{"level":"info","ts":"2021-03-14T07:24:03.290Z","logger":"controller_node","msg":"Getting config from operator configmap"}
{"level":"info","ts":"2021-03-14T07:24:03.292Z","logger":"controller-runtime.controller","msg":"Starting workers","controller":"pod-controller","worker count":1}
{"level":"info","ts":"2021-03-14T07:24:03.292Z","logger":"status_manager","msg":"Checking all nsx-node-agent pods for node condition"}
E0314 07:24:03.292817 1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 704 [running]: …
> Handle pod status StartTime access when it's not initilized

- pkg/controller/pod/pod_controller.go
- pkg/controller/pod/pod_controller_test.go
- pkg/controller/sharedinfo/shared_info.go
- pkg/controller/statusmanager/pod_status.go
- pkg/types/names.go
Sometimes when a nsx-node-agent pod is created and
running for less than 180 seconds, the operator will
try to update the node status twice (firstly set
network-unavailable=true, then sleep and try to set
network-unavailable=false after 180 seconds)[1].
The code has a redundant check before sleeping, and
in the check logic, Get API reads the node status
from cache which may be not synced after the first
update operation was executed, so an unexpected
"Node condition is not changed" will be reported,
then the taints cannot be removed until the removal
logic was triggerred accidentally by another event
from nsx-node-agent pod. This patch will remove the
redundant check.
And we will assume that the data read by client will
eventually be correct, but may be slightly out of
date. So this patch …
> Improve the resync logic for node network status

- pkg/controller/configmap/config.go
This change simply ensures tls.ca is populated in the rendered nsx-secret
only if specified in the secret in the operator namespace
> nsx-secret: render tls.ca only if specified in operator secret

- pkg/controller/node/node_controller.go
- pkg/controller/statusmanager/node_status.go
Previously we only matched the node address via ExternalIP.
This patch will expand the matching range to all node
addresses, including ExternalIP, InternalIP, etc.
Appending some examples of node addresses info:
1. [{ExternalIP 192.168.10.38} {InternalIP 192.168.10.38} {Hostname compute-0}]}
2. [{InternalIP 172.10.0.3} {Hostname vm10-dhcp-0-127}]}
> Expand the matching range for searching node LSP

- pkg/controller/configmap/configmap_controller.go
- pkg/types/names.go
The previous error handling logic is that when the operator hit
error during applying configuration, the reconciler will receive
an error then requeue the request. However, the requeue mechanism
has a potential backoff, that caused the operator may not
immediately respond when the customer correct error in operator's
cluster role.
This patch will additional watch the cluster role change for
the immediate response.
> Immediately respond when the customer correct error in role

- manifest/kubernetes/rhel/ncp-rhel.yaml
- manifest/kubernetes/ubuntu/ncp-ubuntu.yaml
- manifest/openshift4/coreos/ncp-openshift4.yaml
- pkg/controller/configmap/config.go
- pkg/controller/configmap/configmap_controller.go
- pkg/controller/configmap/configmap_controller_test.go
Improve logic for comparing keys in the secret in order to avoid
conditions where empty and missing tls keys (eg.: tls.ca) are interpreted
as differences in the secret.
Also, do not use DeepEqual as there is only need for comparing tls data
in the secret. This will avoid unnecessarily restarting ncp for unrelated
operator secret changes.
Finally do not include tls.ca in the projected volume if not specified in
the operator secret, or empty.
This commit also adds unit tests for secret comparison cases not
previously covered
> Improvements for SecretNotEqual function

- hack/get-kustomize.sh
This commit removes the 'kustomize' binary from the repo
and ensures get-kustomize.sh always leverages the downloaded
version.
Fixes #104
> Prepare assets: Ensure kustomize is dynamically downloaded

- deploy/kubernetes/operator.nsx.vmware.com_ncpinstalls_crd.yaml
- deploy/openshift4/operator.nsx.vmware.com_ncpinstalls_crd.yaml
Change crd version from apiextensions.k8s.io/v1beta1 to
apiextensions.k8s.io/v1, as v1beta1 is deprecated in k8s 1.16 and
removed in k8s 1.22
> Change crd version in deployment file

- pkg/controller/configmap/config.go
Remove force configmap option wait_for_security_policy_sync as true
to use NCP upstream configmap default value
> Remove force wait_for_security_policy_sync True

- pkg/controller/node/node_controller.go
Support # and | in nsx_api_password, but we should make sure
customer won't use in-line comment, eg:
nsx_api_password=123   #comment
ini loader will receive "123   #comment" as nsx_api_password's
value.
Resolves: #69
> Support special char # and | in nsx_api_password

- pkg/controller/pod/pod_controller.go
5 seconds deletion grace period is not enough for nsx-ovs to gracefully
terminate as it (de)activates Network Manager connection profiles.
This is a cherry-pick of commit 9162cce8b9cab4b0064a35c2c7440fc6242843ce
> Set node-agent-pod deletion grace period to 60 seconds

- deploy/kubernetes/operator.nsx.vmware.com_ncpinstalls_crd.yaml
- deploy/kubernetes/operator.nsx.vmware.com_v1_ncpinstall_cr.yaml
- deploy/openshift4/operator.nsx.vmware.com_ncpinstalls_crd.yaml
- deploy/openshift4/operator.nsx.vmware.com_v1_ncpinstall_cr.yaml
- manifest/kubernetes/rhel/ncp-rhel.yaml
- manifest/kubernetes/ubuntu/ncp-ubuntu.yaml
- manifest/openshift4/coreos/ncp-openshift4.yaml
- pkg/apis/operator/v1/ncpinstall_types.go
- pkg/controller/configmap/config.go
- pkg/controller/configmap/config_test.go
- pkg/controller/configmap/configmap_controller.go
- pkg/controller/configmap/configmap_controller_test.go
- pkg/types/names.go
This patch is to allow user to configure NodeSelector for NCP Deployment
by editing operator.nsx.vmware.com_v1_ncpinstall_cr.yaml spec field:
For example, user can add nodeSelector: disktype: ssd to make NCP pod to be
deployed in the node labeled with disktype: ssd. Operator dynamically detects
user-defined spec changes to sync with NCP Deployment once user make changes.
One example for NCP nodeSelector
spec:
nsx-ncp:
nodeSelector:
disktype: ssd
Resolves issue #54
> Add Ncp NodeSelector from NcpInstall CRD

- README.md
- bundle/kubernetes/manifests/operator.nsx.vmware.com_ncpinstalls_crd.yaml
- bundle/openshift4/manifests/operator.nsx.vmware.com_ncpinstalls_crd.yaml
- deploy/kubernetes/operator.nsx.vmware.com_ncpinstalls_crd.yaml
- deploy/kubernetes/operator.nsx.vmware.com_v1_ncpinstall_cr.yaml
- deploy/openshift4/operator.nsx.vmware.com_ncpinstalls_crd.yaml
- deploy/openshift4/operator.nsx.vmware.com_v1_ncpinstall_cr.yaml
- pkg/apis/operator/v1/ncpinstall_types.go
If a node has multiple VirtualNetworkInterfaces attached, the operator
cannot detect which node LSP should be enabled. So the customer should
disable flag "addNodeTag" and tag the node LSP by manually.
> Doc that flag "addNodeTag" should be disabled for node multiple NICs

- pkg/controller/configmap/config.go
Since Container orchestrator adaptor option in configmap:
'adaptor = kubernetes'
is hidden, so it's needed to set default value 'kubernetes' 
of configmap in the code for k8s env.
> Set default coe adaptor for k8s env

- cmd/manager/main.go
- deploy/kubernetes/operator.yaml
- deploy/openshift4/operator.yaml
This patch is to add a command flag for metrics server bindaddress
to make it as a configurable option by users
By default, metrics server is listening to bindaddress at :8080 port, which
could conflict with some user's env settings.
Hence, this patch adds a command flag: metrics-server-bind-address,
whose default value is 8181. User can also change this value from
command line flags as necessary to avoid conflicts with user's env
> Add a command flag to metrics server bindaddress

- manifest/kubernetes/rhel/ncp-rhel.yaml
- manifest/kubernetes/ubuntu/ncp-ubuntu.yaml
- manifest/openshift4/coreos/ncp-openshift4.yaml
This patch is to sync ncp manifest change which adds a NodeName Env
in nsx-kube-proxy so that kube-proxy can get container's nodename.
> Add NodeName Env in nsx-kube-proxy Container

- manifest/kubernetes/rhel/ncp-rhel.yaml
- manifest/kubernetes/ubuntu/ncp-ubuntu.yaml
- manifest/openshift4/coreos/ncp-openshift4.yaml
- pkg/controller/configmap/config.go
- pkg/types/names.go
When use nsx-ovs kernel module, we need to uncomment the volume mounts
for installing nsx-ovs kernel module, otherwise nsx-ncp-bootstrap will
fail to start.
Issue: bug-2884287
> Uncomment volumes when use nsx-ovs kernel module

- bundle/kubernetes/manifests/nsx-container-plugin-operator.clusterserviceversion.yaml
- bundle/openshift4/manifests/nsx-container-plugin-operator.clusterserviceversion.yaml
Sync bundle manifests with latest manifests under directory deploy
for nsx-container-plugin-operator v3.2.1 version in release_3.2.1 branch
> Sync bundle manifests version in 3.2.1 release

- pkg/controller/configmap/config.go
- pkg/controller/configmap/config_test.go
- pkg/controller/configmap/configmap_controller.go
This patch is to enhance log output when user makes configmap change:
1.Log which section is added into or removed from configmap
2.Log configmap option added/uncommented or removed/commented
3.Log configmap option value change
> Add configmap option diff change log

- deploy/kubernetes/operator.nsx.vmware.com_v1_ncpinstall_cr.yaml
- deploy/kubernetes/operator.yaml
- deploy/openshift4/operator.nsx.vmware.com_v1_ncpinstall_cr.yaml
- deploy/openshift4/operator.yaml
The node-role.kubernetes.io/master label is deprecated.
Hence, adding node-role.kubernetes.io/control-plane toleration
for NCP, nsx-ncp-bootstrap and nsx-node-agent to deploy
NCP, nsx-ncp-bootstrap and nsx-node-agent on control plane nodes.
Add this toleration for operator deployment as well.
Resolves issue #191
> Add toleration for control-plane label

- deploy/kubernetes/operator.yaml
- deploy/openshift4/operator.yaml
Nsxcli collect pod logs by using "tier: nsx-networking" label
to select matching pod. This patch is to add "tier: nsx-networking"
label in ncp-operator pod deployment yaml definition to make nsxcli
can collect operator log.
> Add operator log in support bundle

- pkg/controller/node/node_controller.go
Filter node addresses with type `Hostname` and only add IP addresses
to array.
> filter node addresses with type host name

- pkg/controller/node/node_controller.go
This patch will fix the error in the following case:
There's an error while tagging the node port, the operator reports
the error to cluster operator, then the node is removed from the
cluster. If the error is the last one in the cluster operator, it
cannot be cleaned as expected.
> Ensure the error message can be removed after node removal

- manifest/kubernetes/rhel/ncp-rhel.yaml
- manifest/kubernetes/ubuntu/ncp-ubuntu.yaml
- manifest/openshift4/coreos/ncp-openshift4.yaml
This patch is to add host folder of keepalived config and Kubernetes static pod manifest directory mounted in the node agent nsx-ovs container for openshift platform.
> Add host folder mounted in node agent manifest yaml

- pkg/controller/configmap/config.go
The log_file config option in DEFAULT section is used for both nsx-ncp-config and nsx-node-agent-config.
So, the log_file will be used for bootstrap, ncp and node-agent pods once it is set. All pods will write log in the same log_file. However, ncp and node-agent write log_file with ncp user, bootstrap pod write log_file with root user.
The log_file is set in operator configmap, boostrap, ncp and node-agent pod will be restarted. If bootstrap pod create log_file before than ncp/node-agent pods is trying to access. Bootstrap pod creates and write log_file with root users. In such case, the ncp/node-agent will hit Permission denied issue when writing log_file and the ncp/node-agent pod will be crashed.
This patch is to make a workaround solution to fix this issue:
1. Reset log_file to the …
> Reset configmap log_file option

- README.md
- deploy/kubernetes/configmap.yaml
- deploy/openshift4/configmap.yaml
- go.mod
- go.sum
- pkg/controller/configmap/config.go
- pkg/controller/configmap/config_test.go
- pkg/controller/sharedinfo/shared_info.go
Make ncp-operator responsible for inferring adaptor by os-release of host node, and remove coe.adaptor from ConfigMap. Add check for immutable fields to prevent these fields from being changed.
> Add enhancement for ncp-operator config

- pkg/controller/controller.go
Check the returned status from sharedInfo initialization before it is used, as otherwise it fails ungracefully.
> Check if sharedInfo returned err before use

- pkg/controller/configmap/config.go
- pkg/types/defaults.go
It is not necessary to restart nsx-node-agent when some keys are changed in section `k8s` and `coe`. So update the code to only restart nsx-node-agent when specified keys in section `k8s` and `coe` are changed.
> Avoid unnecessary nsx-node-agent restarts

- manifest/kubernetes/rhel/ncp-rhel.yaml
- manifest/kubernetes/ubuntu/ncp-ubuntu.yaml
- manifest/openshift4/coreos/ncp-openshift4.yaml
Remove priorityClass for NCP
ncrease nsx-ncp pod liveness probe timeout to 30 seconds
> Sync manifest change of NCP 4.1.1

- manifest/kubernetes/rhel/ncp-rhel.yaml
- manifest/kubernetes/ubuntu/ncp-ubuntu.yaml
- manifest/openshift4/coreos/ncp-openshift4.yaml
Remove priorityClass for NCP
ncrease nsx-ncp pod liveness probe timeout to 30 seconds
> Sync manifest change of NCP 4.1.1 (#230) 

- deploy/kubernetes/configmap.yaml
- deploy/openshift4/configmap.yaml
- manifest/kubernetes/rhel/ncp-rhel.yaml
- manifest/kubernetes/ubuntu/ncp-ubuntu.yaml
- manifest/openshift4/coreos/ncp-openshift4.yaml
Removing PodSecurityPolicy(PSP) since K8s 1.25 no longer doesn't support PSP
Removing volMount /usr/lib64/libcrypto.so.1.1 in bootstrap pod for OCP4 to support OCP 4.13
> Sync manifest and configmap change of NCP 4.1.2

- .github/workflows/build_tag.yml
- build/Dockerfile
Starting with Go 1.21, the runtime system needs to have a version of glibc "compatible" with the version available at build time. The ubi8 image comes with a very old version of glibc compared to the golang builder. so, the NCP Operator binaries will fail to run and hit GLIBC issue.
To fix this issue, we need to install Golang manually in ubi8 image when making docker build. Moreover, we use Golang 1.19 for Github workflow build action. To align this workflow, we install Golang 1.19 for Github workflow build tag action and Docker image build.
Fix issue:https://github.com/vmware/nsx-container-plugin-operator/issues/237
> Install Golang 1.19 for docker build and release build

- .github/workflows/build_tag.yml
- build/Dockerfile
Starting with Go 1.21, the runtime system needs to have a version of glibc "compatible" with the version available at build time. The ubi8 image comes with a very old version of glibc compared to the golang builder. so, the NCP Operator binaries will fail to run and hit GLIBC issue.
To fix this issue, we need to install Golang manually in ubi8 image when making docker build. Moreover, we use Golang 1.19 for Github workflow build action. To align this workflow, we install Golang 1.19 for Github workflow build tag action and Docker image build.
Fix issue:https://github.com/vmware/nsx-container-plugin-operator/issues/237
CP from https://github.com/vmware/nsx-container-plugin-operator/pull/238
> Install Golang 1.19 for docker build and release build(#238)

- .github/workflows/build_tag.yml
- build/Dockerfile
Starting with Go 1.21, the runtime system needs to have a version of glibc "compatible" with the version available at build time. The ubi8 image comes with a very old version of glibc compared to the golang builder. so, the NCP Operator binaries will fail to run and hit GLIBC issue.
To fix this issue, we need to install Golang manually in ubi8 image when making docker build. Moreover, we use Golang 1.19 for Github workflow build action. To align this workflow, we install Golang 1.19 for Github workflow build tag action and Docker image build.
Fix issue:https://github.com/vmware/nsx-container-plugin-operator/issues/237
CP from https://github.com/vmware/nsx-container-plugin-operator/pull/238
> Install Golang 1.19 for docker build and release build(238)

- .github/workflows/build.yml
- .github/workflows/build_tag.yml
- .github/workflows/test.yml
- Makefile
- build/Dockerfile
- go.mod
- go.sum
- pkg/controller/configmap/config_test.go
This patch is to
1.Upgrade goalng version from 1.19.10 to 1.21.5.
2.Disable CGO for golang compilation to fix UBI8 with libc compatibility issue with golang version >=1.20.
3.Fix an error of config unit test.
> Upgrade golang to 1.21.5 and disable CGO

- pkg/controller/configmap/config.go
- pkg/controller/configmap/config_test.go
keepalived is configured with unicast by default from OC 4.11
> Set enable_ovs_mcast_snooping as false by default

- pkg/controller/configmap/config.go
- pkg/controller/configmap/config_test.go
keepalived is configured with unicast by default from OC 4.11
CP: https://github.com/vmware/nsx-container-plugin-operator/pull/250
> Set enable_ovs_mcast_snooping as false by default(CP#250)

- deploy/kubernetes/configmap.yaml
- deploy/openshift4/configmap.yaml
Adds that enable_mixed_expression_groups is
1. applicable only if NSX version < 4.2.0
2. always set to True if NSX version >= 4.2.0
> Update description of conf opt enable_mixed_expression_groups

- go.mod
- go.sum
- pkg/controller/node/node_controller.go
- pkg/types/utils.go
As NSX 9.0 intends to remove MP APIs, we need to switch to Policy API. This patch makes the changes necessary for node controller Logical Switch related APIs
The patch removes some stale code which is no longer used
Testing Done
------------
- Verified that the Segment Ports for nodes are updated by the operator
- Verified that the operator is running fine
Jira: NCP-601
> Switch to Policy API for Segment and Segment Ports

- bundle/kubernetes/manifests/operator.nsx.vmware.com_ncpinstalls_crd.yaml
- bundle/openshift4/manifests/operator.nsx.vmware.com_ncpinstalls_crd.yaml
- deploy/kubernetes/operator.nsx.vmware.com_ncpinstalls_crd.yaml
- deploy/openshift4/operator.nsx.vmware.com_ncpinstalls_crd.yaml
- pkg/controller/configmap/config.go
- pkg/controller/configmap/configmap_controller.go
There are some scenarios were NCP must be temporarily shut down. This can be done by setting the number of replicas to 0, but the operator currently prevents that.
> Allow NcpReplicas to be set to 0

- manifest/openshift4/coreos/ncp-openshift4.yaml
ncp-openshift4.yaml is outdated and it needs to be update in order to access ingresscontrollers from api group operator.openshift.io for NCP
> Update NCP ClusterRole to access ingresscontrollers

- pkg/controller/configmap/configmap_controller.go
Skip handing nsx-secret and lb-secert when they are not found in the system.
This enhancment will allow users not set nsx-secret and lb-secert, but NCP Operator will not be stuck in keeping fetch them. So, the operator can continue to reconcile process instead of fetching loop.
> Enhance nsx-secret and lb-secert handling
