vmware/nsx-container-plugin-operator

pkg/controller/configmap/configmap_controller.go
pkg/controller/node/node_controller.go
pkg/controller/sharedinfo/shared_info.go

Node controller will use NSX config from operator configmap

Add operator configmap into sharedInfo

---

deploy/configmap.yaml
manifest/cluster-network-15-nsx-secret.yaml
manifest/cluster-network-19-nsx-ncp.yaml
pkg/controller/configmap/config.go
pkg/controller/node/node_controller.go
pkg/types/names.go

1. Support the user configure NSX cert/key/ca in operator
configmap yaml file
2. Node controller can connect to NSX manager via NSX cert/key

Support NSX cert/key/ca

---

pkg/controller/node/node_controller.go

Node controller will get the providerID from OpenShift node.spec,
then use the providerID to achieve the vSphere VM name which is needed
when searching node port.

Fix port not found issue when node name doesn't match vSphere name

---

pkg/controller/configmap/configmap_controller.go

If operator restarts without any config change, need to update sharedInfo before reconciling returns.

Update shared info before comparing with existing config

---

Makefile
README.md
build/Dockerfile

Remove golang middle image from Dockerfile

Build binary from Makefile

---

build/Dockerfile
bundle/nsx-container-plugin-operator.package.yaml
deploy/olm-catalog/0.0.3/nsx-container-plugin-operator.v0.0.3.clusterserviceversion.yaml
version/version.go

- Set labels on container image
- Add license in /licenses directory in operator image
- Add package and CSV CR
- Create metadata bundle directory

Mixed Changes for RH certification

---

deploy/configmap.yaml
deploy/lb-secret.yaml
deploy/nsx-secret.yaml
pkg/controller/configmap/config.go
pkg/controller/configmap/config_test.go
pkg/controller/configmap/configmap_controller.go
pkg/controller/configmap/configmap_controller_test.go
pkg/types/defaults.go

Move certificates to secrets

---

pkg/controller/configmap/config.go

enable grouping feature in openshift by default

Enable Grouping Calculation Notif feature by default

---

pkg/controller/node/node_controller.go

Tier1-segment means the segment who has path
`/infra/tier-1s/<tier-1-id>/segments/<segment-id>`.
Previously we had already supported the infra-segment,
whose path is` /infra/segments/<segment-id>`.

Support tier1-segment port as the node port

---

pkg/controller/configmap/configmap_controller.go
pkg/controller/node/node_controller.go
pkg/controller/sharedinfo/shared_info.go

node_controller will use nsx-secret from shared_info

Add nsx-secret in shared_info

---

pkg/controller/configmap/config.go
pkg/controller/configmap/config_test.go
pkg/controller/configmap/configmap_controller.go
pkg/types/defaults.go

Set MTU in network CRD status
Restart nsx-ncp-bootstrap pods if MTU is changed

Support MTU configuration in NCP Operator

---

pkg/controller/configmap/configmap_controller.go
pkg/controller/pod/pod_controller.go
pkg/controller/pod/pod_controller_test.go
pkg/types/names.go

Restart nsx-node-agent pod if in CLB due to invalid resolv.conf

---

pkg/controller/node/node_controller.go

To avoid tagging wrong port when two ports have the same vm-name and the
same IP addresses:
1. use manager API ListVirtualMachines to get the VM by providerID and
get the VM's property "externalId"
2. use manager API ListVifs to get the Vif by externalId then get the
Vif's property "lport_attachment_id"
3. use manager API ListLogicalPorts to get the logical switch port by
lport_attachment_id
4. get the correct port from the results of 3 according to the address

Search node LSP by provider ID

---

go.mod
go.sum
pkg/controller/node/node_controller.go

The fix depends on vmware/go-vmware-nsxt#32 and
vmware/go-vmware-nsxt#33

Fix the hyperbus_mode lost issue during updating tags

---

pkg/controller/statusmanager/pod_status.go

Fix log indicating NCP replicas status while it's in CLB

---

manifest/kubernetes/rhel/cluster-network-21-nsx-node-agent-psp.yaml
manifest/kubernetes/rhel/cluster-network-32-nsx-node-agent.yaml
manifest/kubernetes/ubuntu/cluster-network-21-nsx-node-agent-psp.yaml
manifest/kubernetes/ubuntu/cluster-network-32-nsx-node-agent.yaml
manifest/openshift4/coreos/cluster-network-22-nsx-node-agent.yaml

Add NET_RAW capability in nsx-node-agent and nsx-kube-proxy

---

manifest/kubernetes/rhel/cluster-network-28-nsx-ncp-version-config.yaml
manifest/kubernetes/ubuntu/cluster-network-28-nsx-ncp-version-config.yaml
manifest/openshift4/coreos/cluster-network-18-nsx-ncp-version-config.yaml

Ensure it reports the latest NCP version.

Update nsx-ncp-version-config ConfigMap

---

olm-catalog/0.2.0/nsx-container-plugin-operator.v0.2.0.clusterserviceversion.yaml
olm-catalog/nsx-container-plugin-operator.package.yaml

Updates the operator CSV for the 0.0.2 image tag

Update CSV for 0.2.0 operator

---

pkg/controller/configmap/config.go

This patch fixes the log message issue and simplifies the judgment logic.

Improve HA disable logic

---

pkg/controller/configmap/configmap_controller.go

Issue brief: 
This verbose logging come from the Reconcile function of configmap_controller, which means there are many resources changes event watched by configmap controller in a short time,  as we see from issue#100,  twice every second or even worse in my testing. 
The **root cause** of this issue: 
There are many **unexpected** Configmap resource change events and Secretr resource change events from namespaces other than nsx-system-operator happened. These event changes also trigger also are pushed to handling queue of Reconcile process. That is why we see this verbose logging output from Reconcile function, since it was called multiple times to handle these events.  This issue usually happens during operator pod startup and configmap render phase. 
Solution of Identification:
By …

Add watchedNameSpace into controller Watch func to filer out unexpected namespace changes for ConfigMap Reconcile

---

pkg/controller/configmap/configmap_controller.go

Correct secret compare function name in consistent with function intention:

Change secret compare func name

---

go.mod
pkg/controller/configmap/configmap_controller.go
pkg/controller/configmap/configmap_controller_test.go

…-bootstrap by updating an existing deployment/daemonset spec.template field to trigger k8s redeploy pods.

Introduce pod rolling update strategy

---

pkg/controller/configmap/config.go
pkg/controller/configmap/config_test.go
pkg/types/defaults.go

There are many options used for bootstrap DS, so move to check section
to restart bootstrap pods

Update sections in BootstrapOptions

---

pkg/apis/operator/v1/ncpinstall_types.go
pkg/controller/configmap/config.go
pkg/controller/node/node_controller.go

This patch is to make change inclusive terminology where appropriate
1.Change offensive term enable/disable to activate/deactivate

Change Inclusive Terminology for NCP Operator

---

deploy/kubernetes/configmap.yaml
deploy/kubernetes/role.yaml
deploy/openshift4/configmap.yaml
deploy/openshift4/role.yaml
manifest/kubernetes/rhel/ncp-rhel.yaml
manifest/kubernetes/ubuntu/ncp-ubuntu.yaml
manifest/openshift4/coreos/ncp-openshift4.yaml

Sync manifests, configmap and role yamls from NCP 3.2.1 branch

Sync NCP3.2.1 manifests, configmap and role

---

bundle/kubernetes/manifests/configmap.yaml
bundle/kubernetes/manifests/nsx-container-plugin-operator.clusterserviceversion.yaml
bundle/kubernetes/manifests/operator.nsx.vmware.com_ncpinstalls_crd.yaml
bundle/openshift4/manifests/configmap.yaml
bundle/openshift4/manifests/nsx-container-plugin-operator.clusterserviceversion.yaml
bundle/openshift4/manifests/operator.nsx.vmware.com_ncpinstalls_crd.yaml

Sync bundle manifests with latest manifests under directory deploy
for nsx-container-plugin-operator v3.2.1 version release in master branch

Sync bundle manifests with deploy ones for v3.2.1

---

manifest/kubernetes/rhel/ncp-rhel.yaml
manifest/kubernetes/ubuntu/ncp-ubuntu.yaml
manifest/openshift4/coreos/ncp-openshift4.yaml

Update NCP manifest with latest NCP on branch master.

sync ncp manifests with latest ncp

---

pkg/controller/node/node_controller.go

The default page size of NSX-T API is 1000. In the scale env,
when the number of nodes is greater than 1000, we need to specify
parameter cursor in multiple queries to get all node information.

Fixing the cursor issue while achieving node

---

manifest/kubernetes/rhel/ncp-rhel.yaml
manifest/kubernetes/ubuntu/ncp-ubuntu.yaml
manifest/openshift4/coreos/ncp-openshift4.yaml

Sync manifests yamls from NCP 4.0.0 branch

Sync NCP 4.0.0 manifests yamls

---

pkg/controller/configmap/configmap_controller.go
pkg/controller/sharedinfo/shared_info.go

Since PodSecurityPolicy is not supported any longer starting k8s >= v1.25.0,
So, it's good that using runtime k8s version decides to apply
PodSecurityPolicy or not. If k8s >= v1.25.0, PodSecurityPolicy resources
will not be applied.

Support dynamic check podSecurityPolicy support

---

deploy/kubernetes/configmap.yaml
deploy/openshift4/configmap.yaml

Sync manifests/configmap yamls from NCP 4.0.1 nsx-jetfire-401 branch to operator master branch

Sync NCP 4.0.1 manifests/configmap yamls

---

deploy/kubernetes/configmap.yaml
deploy/openshift4/configmap.yaml

Sync configmap yamls from NCP 4.1.0 nsx-keeper branch to operator master branch

Sync NCP 4.1.0 configmap yamls

---

pkg/controller/configmap/config.go

Add a warning message when changing coe.adaptor to invalid value.

Add warning message when changing coe.adaptor

---

pkg/controller/configmap/config.go
pkg/types/defaults.go

Reverts vmware/nsx-container-plugin-operator#217

Revert "Avoid unnecessary nsx-node-agent restarts"

---

manifest/openshift4/coreos/ncp-openshift4.yaml

Sync manifest change in NCP 4.1.2

Sync manifiest change in NCP 4.1.2

---

.github/workflows/build.yml
.github/workflows/build_tag.yml
.github/workflows/certification.yml
.github/workflows/test.yml
.github/workflows/upload_release_assets.yml

Versions is use are about to be deprecated, upgrade to latest versions of the above.

Upgrade actions/checkout, actions/setup-go

---

deploy/kubernetes/configmap.yaml
deploy/openshift4/configmap.yaml
manifest/kubernetes/rhel/ncp-rhel.yaml
manifest/kubernetes/ubuntu/ncp-ubuntu.yaml
manifest/openshift4/coreos/ncp-openshift4.yaml

Add enable_ncp_setting_crd option in configmap
Add enable ip_forwared for OCP in bootstrap POD

Sync ncp4.1.2.1 manifest and configmap

---

deploy/kubernetes/configmap.yaml
deploy/openshift4/configmap.yaml
manifest/kubernetes/rhel/ncp-rhel.yaml
manifest/kubernetes/ubuntu/ncp-ubuntu.yaml
manifest/openshift4/coreos/ncp-openshift4.yaml

Sync ncp4.2.0 manifest and configmap

Sync ncp4.2.0 manifest and configmap

---

manifest/openshift4/coreos/ncp-openshift4.yaml

Sync OC manifest for removing redundant volume mounts

Sync OC manifest for running d-bus commands on host
